/**
* AdminJS Custom Javascript file
* (sails/assets/adminbro/adminbro.js)
*
* You can place any custom front-end js code below to make it valid for adminPanel screens.
*
* > This file is mainly useful for configuring the javascript that is used in Panel
*
* For all available options, see:
* https://github.com/okankurtulus/sails-hook-adminjs-panel
*/

const info = 'Generated by sails-hook-adminjs-panel';
console.log(info);